### ISSUE TITLE
gradio demo saves black img

### ISSUE THREAD

**Issue by Skwarson96** [LiheYoung/Depth-Anything#107]
Hello
I think I encountered a bug while testing the gradio demo. After downloading the resulting photo, I get a black image. I suspect the bug may be [here](https://github.com/LiheYoung/Depth-Anything/blob/e7ef4b4b7a0afd8a05ce9564f04c1e5b68268516/app.py#L76) (in app.py) : 
`raw_depth = Image.fromarray(depth.cpu().numpy().astype('uint16'))` 
when I change these line to:
`raw_depth = Image.fromarray(depth.cpu().numpy().astype('uint8'))`
downloading works fine

**Comment by LiheYoung** [comment]
Hi, actually this is an intentional practice to save it as ``uint16`` and it is expected that the downloaded raw uint16 disparity map is all black *visually*. 

We choose ``uint16`` because the raw output disparity can be much larger than 256, which is out of range for ``uint8``. To better visualize them, you can easily read the downloaded ``uint16`` map and re-normalize them to 0-255, similar to the practice we used for Gradio visualization.
