### ISSUE TITLE
Output image resolution of metric depth other than multiple of 14

### ISSUE THREAD

**Issue by a-kungwani** [LiheYoung/Depth-Anything#146]
Hi @LiheYoung, Thank you for your great work and contribution.

I am trying to feed an image of resolution 1280x720p without resizing it. The model is expecting the image resolution in multiples of 14. Is it possible to change the parameter to other number which is a multiple of 720. I am trying to get the output resolution of same 1280x720p. 
Also, it is possible to train the encoder with another patch size of 16 maybe?
 
Thank you in advance

**Comment by heyoeyo** [comment]
There are probably a few different options:
1. The simplest & highest quality option would be to just run the model using a resolution like 1288x728 (multiples of 14, just above the original resolution), and then scale the resulting depth map back down to the original size. For example, the run.py script does [this sort of scaling](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/run.py#L78).
2. Use a model that has a patch size of 16, like the older [MiDaS](https://github.com/isl-org/MiDaS) models (e.g. the BEiT-large-512 model).
3. If you really wanted to avoid resizing, you can instead pad the input image to get it to a size of 1288x728 (for example). Then after running the depth prediction, you can crop out the padded part.
4. It would be possible to modify the patch embedding module to [include padding directly](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/dinov2/layers/patch_embed.py#L66), so that it could directly handle other image sizes. However, this would probably require changes elsewhere in the code (for example, getting rid of the [sizing checks](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/dinov2/layers/patch_embed.py#L73-L74))

**Comment by LiheYoung** [comment]
Hi @heyoeyo, first please allow us to express our deepest gratitude. We are sincerely grateful to you for your kind and tremendous help in addressing and discussing multiple issues in this repo! It is our great honor to have you here. Thank you.

And hi @a-kungwani, as @heyoeyo has suggested, we also recommend you to try the first option. You can follow the file [run.py](https://github.com/LiheYoung/Depth-Anything/blob/main/run.py) to do so. And if you want to avoid resizing as much as possible, you can try to use a larger input resolution defined in the transform function: https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/run.py#L39-L51
You can change the ``width`` and ``height`` to ``720`` and ``1280`` respectively.

**Comment by a-kungwani** [comment]
Hi @heyoeyo, Hi @LiheYoung. I Thank you both for your detailed explaination and guide to the issue. I'll go through it!
