### ISSUE TITLE
Request for Access to Teacher Model Weights for Pseudo-Label Generation

### ISSUE THREAD

**Issue by SoniaShona** [LiheYoung/Depth-Anything#147]
Hi @LiheYoung, Thank you for your amazing work and contribution.

Is it possible to have access to Teacher model weights ? I have an unlabeled dataset and aim to leverage the Teacher model to generate pseudo-labels for subsequent fine-tuning of the Student model.

Thank you in advance for your assistance.

**Comment by LiheYoung** [comment]
Hi @SoniaShona, actually our released Depth-Anything-Large model is better than its teacher model, because the teacher model is only trained on labeled images, while the released model is trained on labeled and unlabeled images. You can refer to the Table 9 in our paper. Therefore, you can use the released model for pseudo labeling.
